// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Brand: typeof import('./src/components/Brand.vue')['default']
    ContentsTable: typeof import('./src/components/ContentsTable.vue')['default']
    DataDeck: typeof import('./src/components/DataDeck.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    GameOfLife: typeof import('./src/components/GameOfLife.vue')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    Kaomoji: typeof import('./src/components/Kaomoji.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Period: typeof import('./src/components/Period.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PrintButton: typeof import('./src/components/PrintButton.vue')['default']
    ProdPercent: typeof import('./src/components/ProdPercent.vue')['default']
    RenderFeed: typeof import('./node_modules/@islands/feed/dist/render-feed')['RenderFeed']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteTitle: typeof import('./src/components/SiteTitle.vue')['default']
    Subtitle: typeof import('./src/components/Subtitle.vue')['default']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
  }
}
