// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AsciiArt: typeof import('./src/components/AsciiArt.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    Kaomoji: typeof import('./src/components/Kaomoji.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    SiteTitle: typeof import('./src/components/SiteTitle.vue')['default']
    Subtitle: typeof import('./src/components/Subtitle.vue')['default']
  }
}

export { }
