// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsciiArt: typeof import('./src/components/AsciiArt.vue')['default']
    Brand: typeof import('./src/components/Brand.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    GameOfLife: typeof import('./src/components/GameOfLife.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    Kaomoji: typeof import('./src/components/Kaomoji.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Period: typeof import('./src/components/Period.vue')['default']
    ReferenceIndex: typeof import('./src/components/ReferenceIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteTitle: typeof import('./src/components/SiteTitle.vue')['default']
    Subtitle: typeof import('./src/components/Subtitle.vue')['default']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
  }
}
